"""Versioned Phase 2B correction generated only from saved development predictions."""
from pathlib import Path
import argparse,hashlib,json
from datetime import datetime,timezone
import numpy as np,pandas as pd,yaml
from sklearn.metrics import average_precision_score
from .temporal_validation import basic,paired_bootstrap,validate_paired_predictions,corrected_evidence_label
ROOT=Path(__file__).resolve().parents[3]
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def write(p,v):Path(p).parent.mkdir(parents=True,exist_ok=True);Path(p).write_text(json.dumps(v,indent=2,default=str),encoding="utf-8")
def lift(y,s):
 ap=average_precision_score(y,s);prev=float(np.mean(y));return {"prevalence":prev,"average_precision":ap,"ap_lift_ratio":ap/prev,"ap_absolute_lift_over_prevalence":ap-prev}
def main():
 p=argparse.ArgumentParser();p.add_argument("--config",required=True);a=p.parse_args();c=yaml.safe_load(Path(a.config).read_text());base=ROOT/c["paths"]["report_dir"];out=base/"correction_v1";art=ROOT/c["paths"]["artifact_dir"];predpath=art/"development_predictions.parquet"
 if out.exists():raise FileExistsError("correction_v1 exists; overwrite prohibited")
 pred=pd.read_parquet(predpath); folds=json.loads((base/"development_fold_manifest.json").read_text()); old={x.name:sha(x) for x in base.glob("*.json")}; results={}; lifts={}; boot={}; labels={}
 for family in c["models"]:
  s=pred[(pred.model_name==family)&(pred.feature_contract=="strict")];e=pred[(pred.model_name==family)&(pred.feature_contract=="expanded")];s,e=validate_paired_predictions(s,e)
  foldrows=[]; sl=[];el=[]
  for fold in [x["id"] for x in c["folds"]]:
   sf=s[s.fold_id==fold];ef=e[e.fold_id==fold]; ls=lift(sf.y_true,sf.y_score);le=lift(ef.y_true,ef.y_score);sl.append(ls);el.append(le);foldrows.append({"fold_id":fold,"rows":len(sf),"prevalence":ls["prevalence"],"strict_ap":ls["average_precision"],"expanded_ap":le["average_precision"],"delta_ap":le["average_precision"]-ls["average_precision"],"strict_ap_lift_ratio":ls["ap_lift_ratio"],"expanded_ap_lift_ratio":le["ap_lift_ratio"],"strict_ap_absolute_lift":ls["ap_absolute_lift_over_prevalence"],"expanded_ap_absolute_lift":le["ap_absolute_lift_over_prevalence"]})
  macro={"strict_ap":float(np.mean([x["average_precision"] for x in sl])),"expanded_ap":float(np.mean([x["average_precision"] for x in el])),"strict_ap_lift_ratio":float(np.mean([x["ap_lift_ratio"] for x in sl])),"expanded_ap_lift_ratio":float(np.mean([x["ap_lift_ratio"] for x in el])),"strict_ap_absolute_lift":float(np.mean([x["ap_absolute_lift_over_prevalence"] for x in sl])),"expanded_ap_absolute_lift":float(np.mean([x["ap_absolute_lift_over_prevalence"] for x in el]))};macro["delta_ap"]=macro["expanded_ap"]-macro["strict_ap"]
  ps=lift(s.y_true,s.y_score);pe=lift(e.y_true,e.y_score);pooled={"strict_ap":ps["average_precision"],"expanded_ap":pe["average_precision"],"delta_ap":pe["average_precision"]-ps["average_precision"],"pooled_prevalence":ps["prevalence"],"strict_ap_lift_ratio":ps["ap_lift_ratio"],"expanded_ap_lift_ratio":pe["ap_lift_ratio"],"strict_ap_absolute_lift":ps["ap_absolute_lift_over_prevalence"],"expanded_ap_absolute_lift":pe["ap_absolute_lift_over_prevalence"]}
  if not np.isclose(macro["delta_ap"],np.mean([x["delta_ap"] for x in foldrows]),atol=1e-15):raise ValueError("Macro AP reconciliation failed")
  identical=np.allclose(s.y_score,e.y_score,rtol=0,atol=1e-12); b=paired_bootstrap(s.y_true.to_numpy(),s.y_score.to_numpy(),e.y_score.to_numpy(),1000,42); improved=sum(x["delta_ap"]>0 for x in foldrows);label=corrected_evidence_label(pooled["delta_ap"],b["delta_ap"]["lower"],improved,False,identical=identical)
  labels[family]={"label":label,"asof_semantics_proven":False,"reason":"Strict and Expanded predictions are equivalent" if identical else "Development improvement exists but approval-time availability is unverified"};results[family]={"folds":foldrows,"macro":macro,"pooled":pooled,"macro_identity_verified":True,"strict_mean_roc_auc":float(np.mean([basic(x.y_true,x.y_score)["roc_auc"] for _,x in s.groupby("fold_id")])),"expanded_mean_roc_auc":float(np.mean([basic(x.y_true,x.y_score)["roc_auc"] for _,x in e.groupby("fold_id")])),"strict_mean_brier":float(np.mean([basic(x.y_true,x.y_score)["brier_score"] for _,x in s.groupby("fold_id")])),"expanded_mean_brier":float(np.mean([basic(x.y_true,x.y_score)["brier_score"] for _,x in e.groupby("fold_id")]))};boot[family]=b
 audit_old=json.loads((base/"feature_availability_audit.json").read_text()); details=[]
 sources={"payment_record_count":("olist_order_payments_dataset","payment_sequential","count"),"max_payment_installments":("olist_order_payments_dataset","payment_installments","max"),"total_payment_value":("olist_order_payments_dataset","payment_value","sum"),"item_count":("olist_order_items_dataset","order_item_id","count"),"unique_product_count":("olist_order_items_dataset","product_id","count distinct"),"unique_seller_count":("olist_order_items_dataset","seller_id","count distinct"),"total_item_price":("olist_order_items_dataset","price","sum"),"total_freight_value":("olist_order_items_dataset","freight_value","sum"),"mean_freight_value":("olist_order_items_dataset","freight_value","mean"),"max_freight_value":("olist_order_items_dataset","freight_value","max"),"product_category_diversity":("items + products","product_category_name","count distinct"),"mean_product_weight_g":("items + products","product_weight_g","mean"),"mean_product_length_cm":("items + products","product_length_cm","mean"),"mean_product_height_cm":("items + products","product_height_cm","mean"),"mean_product_width_cm":("items + products","product_width_cm","mean")}
 for name in c["retrospective_expanded_features"]:
  table,col,agg=sources[name];details.append({"final_feature_name":name,"source_table":table,"source_columns":[col],"join_key":"order_id","aggregation_rule":agg,"cardinality_contract":"one row per eligible order after pre-join aggregation","raw_event_timestamp":"no source snapshot timestamp provided","prediction_timestamp":"order_approved_at","earliest_known_time":"unverified in final export","mutable_after_approval":"not ruled out","historical_snapshot_provided":False,"availability_at_approval_proven":False,"evidence_paths":["docs/olist_asof_feature_contract.md","docs/olist_expanded_sensitivity_contract.md","docs/olist_join_aggregation_contract.md"],"availability_classification":"UNVERIFIED_ASOF","eligibility_decision":"retrospective sensitivity only","primary_asof":False,"retrospective_only":True,"excluded":False,"reason":"Contract B authorizes an upper-bound sensitivity; immutable approval-time availability is unverified","leakage_risk":"snapshot revision / final-export availability","missing_value_handling":"training-fold median imputation when missing","cold_start_handling":"training-fold median imputation","final_model_column_name":name})
 feature_audit={"strict_core":c["strict_features"],"proven_primary_asof_expanded":[],"retrospective_only_expanded":c["retrospective_expanded_features"],"excluded_contract_candidates":[x for x in audit_old["candidates"] if not x["retrospective_allowed"]],"forbidden":"defined unchanged in configs/olist_feature_contract_v1.yaml","whitelist_sha256":audit_old["whitelist_sha256"],"whitelist_locked_before_original_training":True,"features":details,"statement":"No expanded feature is currently approved as a proven primary as-of production feature."}
 out.mkdir(parents=True);write(out/"corrected_evidence_labels.json",labels);write(out/"corrected_ap_reconciliation.json",results);write(out/"corrected_ap_lift.json",{f:{"folds":v["folds"],"macro":v["macro"],"pooled":v["pooled"]} for f,v in results.items()});write(out/"corrected_paired_bootstrap.json",boot);write(out/"complete_fifteen_feature_audit.json",feature_audit)
 definitions={"macro_ap":"unweighted mean of the three fold AP values","pooled_ap":"Average Precision over concatenated out-of-fold predictions","macro_delta_ap":"macro expanded AP minus macro strict AP","pooled_delta_ap":"pooled expanded AP minus pooled strict AP","ap_lift_ratio":"AP divided by same-fold prevalence","ap_absolute_lift_over_prevalence":"AP minus same-fold prevalence","previous_0_014504":"mean of global row-bootstrap pooled delta replicates; a pooled estimand mislabeled beside macro AP means","previous_1_269":"mean across folds of expanded AP divided by each fold prevalence (macro expanded AP lift ratio)"};write(out/"metric_definitions.json",definitions)
 err={"created_utc":datetime.now(timezone.utc).isoformat(),"status":"COMPLETE","original_artifact_hashes":old,"development_prediction_sha256":sha(predpath),"model_hashes":{str(x.relative_to(ROOT)).replace("\\","/"):sha(x) for x in (art/"models").glob("*")},"corrected_outputs":[],"models_trained":False,"test_reopened":False};write(out/"erratum.json",err)
 doc="# Phase 2B Corrective Reporting Erratum\n\nThis revision preserves the original artifacts and recalculates reporting from the unchanged development predictions. Correct labels are Dummy `NO_INCREMENTAL_SIGNAL`; Logistic Regression, CatBoost, and LightGBM `INCONCLUSIVE_INCREMENTAL_SIGNAL`. No expanded feature has proven approval-time semantics.\n\nThe previous `0.014504` was the mean of bootstrap replicates for a pooled out-of-fold delta, displayed beside macro fold means; it was a valid nearby pooled estimand but mislabeled and its point definition was improper. Corrected outputs separate macro and pooled estimands. The previous `1.269` is the macro expanded AP lift ratio: the mean of fold AP/prevalence ratios.\n\nNo models were trained, no predictions or model artifacts were rewritten, and the consumed Test set was not reopened.\n";(ROOT/"docs/phase2b_olist_sensitivity_erratum.md").write_text(doc,encoding="utf-8")
 print(json.dumps({"correction_status":"COMPLETE","output":str(out.relative_to(ROOT)),"models_trained":False},indent=2))
if __name__=="__main__":main()
